on: push

jobs: 
  my-second-job:
    runs-on: ubuntu-latest
    steps: 
    - name: python  
      run: |
        import os 
        print(len(os.getenv('MY_VAR')))
        echo $MY_VAR
      shell: python
      env: 
        MY_VAR: ${{ secrets.MY_SECRET }}
   
